### ISSUE TITLE
Only beat detection possible?

### ISSUE THREAD

**Issue by Joey-1970** [engineertype/MSGEQ7#3]
Hello Peter,

I find your MSGE7 breakout Board on Ebay.  For my project, I only need a beat detection (digital not PWM) to trigger some other things and calculate the BPM - but this in high quality. My first attempt was this project:
https://create.arduino.cc/projecthub/Joao_Claro/arduino-beat-detector-d0a21f
...but the result is highly dependent on the line in signal strength.

Can your hardware do this digital beat detection in high quality and in a range independently from the lini in signal strength?

Joey

**Comment by engineertype** [comment]
Hi,

You should take a look at the MSGEQ7 datasheet to figure out if this will work for you.  You're trying to detect a low-frequency signal, and I'm not sure this IC works that low.

Peter
